# Generated by Django 5.1.5 on 2025-01-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0003_remove_userdefaults_rst_rcvd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qsolog",
            name="srx",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="qsolog",
            name="stx",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
