# Generated by Django 5.1.5 on 2025-01-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0005_alter_qsolog_options_alter_savedinput_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qsolog",
            name="gridsquare",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="qsolog",
            name="my_gridsquare",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="userdefaults",
            name="my_gridsquare",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
